### ISSUE TITLE
Error on r3stack website: cannot signup

### ISSUE THREAD

**Issue by josephdburdick** [r3stack/r3stack#13]
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app_b17eebb232a4d970c8ff.js:20 Uncaught (in promise) TypeError: Failed to fetch(…)
```

**Comment by morningrat** [comment]
I am glad to know it's not just me.

**Comment by Bartekus** [comment]
I'm sorry for the delay, I'm aware of this and I'm nearly done with the patch but it's been sluggish due to being sick and sleeping longer than usual. Sorry, will fix it asap!
