### ISSUE TITLE
clean up https://angel.co/r3stack

### ISSUE THREAD

**Issue by tomByrer** [r3stack/r3stack#2]
`Full JavaScrip stack` +t
`Project pilot deployment at: rel="nofollow" target="_blank">http://meatier.io`

**Comment by Bartekus** [comment]
I know much more needs to be done in that department but I've cleaned up few things, especially the ones that you have mentioned.
Thank you @tomByrer !

**Comment by Bartekus** [comment]
We'll be cleaning up the profile in the next couple of day. For now I'll close this issue but feel free to reopen it.
